// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2pvxLX_LJKYjdhVPBXOGE9ISgxkdZTWc',
    appId: '1:735607806056:web:358e0245f119f3458483dd',
    messagingSenderId: '735607806056',
    projectId: 'pasarpro-4e996',
    authDomain: 'pasarpro-4e996.firebaseapp.com',
    storageBucket: 'pasarpro-4e996.firebasestorage.app',
    measurementId: 'G-JFPGC2GJQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLlc2mS45NwyQuNE7FM3-Hr5B7aiuFMD0',
    appId: '1:735607806056:android:f4b1671fad7068968483dd',
    messagingSenderId: '735607806056',
    projectId: 'pasarpro-4e996',
    storageBucket: 'pasarpro-4e996.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBYdBWTTY5rFVm_2u-oMnbfKYtPIaRFqY',
    appId: '1:735607806056:ios:b849e98d37970fda8483dd',
    messagingSenderId: '735607806056',
    projectId: 'pasarpro-4e996',
    storageBucket: 'pasarpro-4e996.firebasestorage.app',
    iosClientId: '735607806056-bhskud06otg4dnn610j8u9o8bt3k1gil.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasarpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBYdBWTTY5rFVm_2u-oMnbfKYtPIaRFqY',
    appId: '1:735607806056:ios:b849e98d37970fda8483dd',
    messagingSenderId: '735607806056',
    projectId: 'pasarpro-4e996',
    storageBucket: 'pasarpro-4e996.firebasestorage.app',
    iosClientId: '735607806056-bhskud06otg4dnn610j8u9o8bt3k1gil.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasarpro',
  );

}